name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  CodeFormatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo apt-get install clang-format

    - name: Run formatting style check
      run: ./.github/bin/run-clang-format.sh
